version: '2'

services:
  postgres:
    image: postgres:9.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=loja-virtual
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres